### ISSUE TITLE
yolov3-ocr.cfg does not have down_stride

### ISSUE THREAD

**Issue by chenscottus** [ttanzhiqiang/onnx_tensorrt_project#12]
Hi, I tried to transfer yolo3-spp pt file to onnx, and here is the error:

Traceback (most recent call last):
  File "Libtorch_yolo_to_onnx.py", line 779, in <module>
    main()
  File "Libtorch_yolo_to_onnx.py", line 771, in main
    model_def = builder.build_onnx_graph(
  File "Libtorch_yolo_to_onnx.py", line 353, in build_onnx_graph
    major_node_specs = self._make_onnx_node(layer_name, layer_dict)
  File "Libtorch_yolo_to_onnx.py", line 426, in _make_onnx_node
    node_creators[layer_type](layer_name, layer_dict)
  File "Libtorch_yolo_to_onnx.py", line 729, in _make_yolo_node
    down_stride = int(layer_dict['down_stride'])
KeyError: 'down_stride'

many thanks!

-Scott

**Comment by chenscottus** [comment]
The python file - libtorch_onnx_tensorrt_yolo

**Comment by ttanzhiqiang** [comment]
look https://github.com/ttanzhiqiang/onnx_tensorrt_project/blob/main/model/darknet_onnx_tensorrt_yolo/yolov3.cfg

**Comment by chenscottus** [comment]
yolov3 and yolov3-spp are different. yolov3-spp does not have that. In what you provide about Libtorch_yolo_to_onnx.py and yolov3-ocr.cfg also have the same issue.

**Comment by ttanzhiqiang** [comment]
Using netron, view the network.
In your yolo Plugin，add down_stride(down_stride = (input / output_feature)).
